services:
  CppEnv:
    image: gcc:latest
    container_name: cppenv
    volumes:
      - ./src:/src
    working_dir: /src
    command: >
      bash -c "gcc -std=c11 linklist.c -o linklist &&
               ./linklist &&
               g++ -std=c++20 main.cpp -o main &&
               ./main"