services:
  CppEnv:
    image: gcc:latest
    container_name: cppenv
    volumes:
      - ./src:/src
    working_dir: /src
    command: >
      bash -c "gcc -std=c99 kahan_sum.c -o kahan_sum
              ./kahan_sum"