services:
  CppEnv:
    image: gcc:latest
    container_name: cppenv
    volumes:
      - ./src:/src
    working_dir: /src
    command: >
      bash -c "gcc -std=c99 main.c -o main
              ./main"